[theme]
base = "light"
primaryColor = "#00796B"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#EEF4F3"
textColor = "#172B33"
font = "sans serif"

[server]
headless = true
maxUploadSize = 10
enableXsrfProtection = true

[client]
showErrorDetails = false
